version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  testphp72:
    image: shyim/shopware-demo
    environment:
      - VIRTUAL_HOST=foo.localhost
      - VIRTUAL_SSL=0