version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  testphp72:
    image: shyim/nginx-static:autoindex
    volumes:
      - ./:/var/www/html
    environment:
      - VIRTUAL_HOST=foo.localhost